spring:
  config:
    activate:
      on-profile: prod

  # MySQL 데이터베이스 설정 (시크릿 정보는 application-secret.yml에서 가져옴)
  datasource:
    url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate  # 운영 환경에서는 validate 사용
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        show_sql: false

  # 개발 도구 비활성화
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

# 운영 환경 로깅 설정
logging:
  level:
    root: INFO
    com.example.shop: INFO
