spring:
  config:
    activate:
      on-profile: dev

  # H2 데이터베이스 설정
  datasource:
    url: jdbc:h2:tcp://localhost/~/freemarket
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
    defer-datasource-initialization: true

  # H2 콘솔 활성화
  h2:
    console:
      enabled: true
      path: /h2-console # 콘솔 접근 URL 경로를 설정
      settings:
        web-allow-others: false # 로컬 머신에서만 콘솔에 접근할 수 있도록 제한

  # 개발 편의를 위한 DevTools 설정
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# 개발 환경 로깅 설정
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com.example.shop: debug
    org.springframework.security: debug

# 파일 업로드 경로 설정
file:
  upload-dir: /Users/taeheon/Documents/school/capstone/images # 원본 이미지 저장 경로
  thumbnail-dir: /Users/taeheon/Documents/school/capstone/thumbnails # 썸네일 저장 경로
