spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${oauth2.google.client-id}
            client-secret: ${oauth2.google.secret}
            scope:
              - email
              - profile
              - openid
            redirect-uri: "{baseUrl}/login/oauth2/code/google" # baseUrl은 동적 치환
            client-name: Google
          
          kakao:
            client-id: ${oauth2.kakao.client-id}
            client-secret: ${oauth2.kakao.secret}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
              - openid
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-name: Kakao
          
          naver:
            client-id: ${oauth2.naver.client-id}
            client-secret: ${oauth2.naver.secret}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            client-name: Naver
        
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json # OIDC 추가
            user-name-attribute: sub
          
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
