spring:
  profiles:
    active: dev # 기본적으로 dev 환경 사용 (개발 시)
    include: secret # secret 설정 포함

  # 공통 설정
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true

logging:
  level:
    com.freemarket.freemarket: info
