spring:
  profiles:
    active: dev # 기본적으로 dev 환경 사용 (개발 시)
    include: secret # secret 설정 포함

  # 공통 설정
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com # 사용할 서버
    port: 587
    username: ${mail.username} # 메일을 보내는 계정
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 5000

server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true

logging:
  level:
    com.freemarket.freemarket: info
